version: '3'
services:
  redis:
    image: redis:6.2.6
    container_name: redis-tiny
    command: redis-server --appendonly yes
    volumes:
      - ./redis-tiny/data:/data #数据文件挂载
    ports:
      - 6379:6379
  mall-tiny:
    image: mall-tiny/mall-tiny:1.0.0-SNAPSHOT
    container_name: mall-tiny
    links:
      - redis:redis
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - 'spring.profiles.active=prod'
      - 'spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false'
      - 'spring.datasource.username=root'
      - 'spring.datasource.password=123456'
      - 'spring.redis.host=redis'
    volumes:
      - /etc/localtime:/etc/localtime
      - ./app/mall-tiny/logs:/var/logs